// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SpendSmart.Data;

#nullable disable

namespace SpendSmart.Data.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    [Migration("20250721064323_AddressedTriangularRelations")]
    partial class AddressedTriangularRelations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.7");

            modelBuilder.Entity("SpendSmart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<int>("SubTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("SubTypeId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("SpendSmart.Models.ProductType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ProductTypeName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProductTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductTypeName = "Apparel"
                        },
                        new
                        {
                            Id = 2,
                            ProductTypeName = "Mobile Phone"
                        },
                        new
                        {
                            Id = 3,
                            ProductTypeName = "Laptop"
                        },
                        new
                        {
                            Id = 4,
                            ProductTypeName = "Stationery"
                        },
                        new
                        {
                            Id = 5,
                            ProductTypeName = "Headphones"
                        });
                });

            modelBuilder.Entity("SpendSmart.Models.SubType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ProductTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SubTypeName")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProductTypeId");

                    b.ToTable("SubTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ProductTypeId = 1,
                            SubTypeName = "T-Shirt"
                        },
                        new
                        {
                            Id = 2,
                            ProductTypeId = 1,
                            SubTypeName = "Jeans"
                        },
                        new
                        {
                            Id = 3,
                            ProductTypeId = 2,
                            SubTypeName = "iPhone"
                        },
                        new
                        {
                            Id = 4,
                            ProductTypeId = 2,
                            SubTypeName = "Android"
                        },
                        new
                        {
                            Id = 5,
                            ProductTypeId = 3,
                            SubTypeName = "Gaming Laptop"
                        },
                        new
                        {
                            Id = 6,
                            ProductTypeId = 3,
                            SubTypeName = "Ultrabook"
                        },
                        new
                        {
                            Id = 7,
                            ProductTypeId = 4,
                            SubTypeName = "Notebook"
                        },
                        new
                        {
                            Id = 8,
                            ProductTypeId = 4,
                            SubTypeName = "Pen"
                        },
                        new
                        {
                            Id = 9,
                            ProductTypeId = 5,
                            SubTypeName = "Wireless"
                        },
                        new
                        {
                            Id = 10,
                            ProductTypeId = 5,
                            SubTypeName = "Wired"
                        });
                });

            modelBuilder.Entity("SpendSmart.Models.Product", b =>
                {
                    b.HasOne("SpendSmart.Models.SubType", "SubType")
                        .WithMany()
                        .HasForeignKey("SubTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SubType");
                });

            modelBuilder.Entity("SpendSmart.Models.SubType", b =>
                {
                    b.HasOne("SpendSmart.Models.ProductType", "ProductType")
                        .WithMany()
                        .HasForeignKey("ProductTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProductType");
                });
#pragma warning restore 612, 618
        }
    }
}
